schema:
  format:
    openapi: "3.0.0"
  service_input_type: "ServiceSettings"
  pipeline_input_type: "PipelineSettings"

  types:
    ServiceSettings:
      type: object
      description: "Input properties for a loadbalanced Fargate service"
      properties:
        port:
          type: number
          description: "The port the application serves traffic on"
          default: 8080
          minimum: 0
          maximum: 65535
        health_check_path:
          type: string
          description: "The path used to perform an HTTP health check"
          default: "/"
          minLength: 1
          maxLength: 200
        desired_count:
          type: number
          description: "The default number of Fargate tasks you want running"
          default: 1
          minimum: 1
        task_size:
          type: string
          description: "The size of the task you want to run"
          enum: ["x-small", "small", "medium", "large", "x-large"]
          default: "x-small"
        image:
          type: string
          description: "The name/url of the container image"
          default: "ealen/echo-server:0.5.1"
          minLength: 1
          maxLength: 200

    PipelineSettings:
      type: object
      description: "Pipeline input properties"
      properties:
        app_directory:
          type: string
          description: "The sub-directory where the application code is located"
          minLength: 1
          maxLength: 100
          default: "."
        unit_test_command:
          type: string
          description: "The command to run to unit test the application code"
          default: "echo 'No tests'"
          minLength: 1
          maxLength: 200
        environment_account_ids:
          type: string
          pattern: '^$|^\d{12}(,\d{12})*$'
          description: "The environment account ids for service instances using cross account environment, separated by ,"
          default: ""
          maxLength: 200
      required:
        - app_directory
